### ISSUE TITLE
Adding tw`` to an element for the first time causes the extension to become unresponsive

### ISSUE THREAD

**Issue by timfee** [Arthie/vscode-tailwindcssinjs#2]
See attached video (and CPU dump), basically, I'm forced to reload the window any time I try to add a new ` tw=`` ` tag to an element inside of a `.tsx` file. 

1. Create a new element with the `css` prop, such as ```<span css={tw`m-0`}>```
2. Autocomplete doesn't load, and attempting to apply all fixes hangs, forcing a window reload.
3. If you cancel the pending fix, save anyway, reload the window, and resume editing the new element, autocomplete becomes available and things function normally.

Does this appear to be related to this extension?

CPU dump: [Arthie.vscode-tailwindcssinjs-unresponsive.cpuprofile.txt](https://github.com/Arthie/vscode-tailwindcssinjs/files/5145447/Arthie.vscode-tailwindcssinjs-unresponsive.cpuprofile.txt)

Repro .MOV: [Repro Steps.mov.zip](https://github.com/Arthie/vscode-tailwindcssinjs/files/5145449/Repro.Steps.mov.zip)

My extension list:
```
andrewmcodes.tailwindcss-extension-pack-1.0.0/
arthie.vscode-tailwindcssinjs-0.1.3/
austenc.tailwind-docs-1.3.0/
bradlc.vscode-tailwindcss-0.4.3/
christian-kohler.npm-intellisense-1.3.0/
christian-kohler.path-intellisense-2.2.1/
codeandstuff.package-json-upgrade-1.2.0/
coenraads.bracket-pair-colorizer-1.0.61/
coenraads.bracket-pair-colorizer-2-0.2.0/
davidanson.vscode-markdownlint-0.36.3/
dbaeumer.vscode-eslint-2.1.8/
deepscan.vscode-deepscan-1.10.2/
eamodio.gitlens-10.2.2/
ecmel.vscode-html-css-0.2.3/
editorconfig.editorconfig-0.15.1/
eg2.vscode-npm-script-0.3.13/
esbenp.prettier-vscode-5.5.0/
fallenmax.styled-components-extractor-0.0.6/
github.vscode-pull-request-github-0.19.0/
heybourn.headwind-1.7.0/
iocave.customize-ui-0.1.47/
iocave.monkey-patch-0.1.10/
jpoissonnier.vscode-styled-components-0.0.30/
kettanaito.nako-0.1.2/
luyizhi.vscode-graphql-0.0.4/
macieklad.tailwind-sass-syntax-1.2.1/
muhajirdev.tailwind-styled-snippets-0.2.1/
muhajirframe.tailwind-styled-snippets-0.2.1/
oderwat.indent-rainbow-7.4.0/
prisma.vscode-graphql-0.3.1/
rbbit.typescript-hero-3.0.0/
redhat.vscode-yaml-0.10.1/
richie5um2.vscode-sort-json-1.18.0/
ritwickdey.liveserver-5.6.1/
shardulm94.trailing-spaces-0.3.1/
steoates.autoimport-1.5.3/
stylelint.vscode-stylelint-0.85.0/
tht13.html-preview-vscode-0.2.5/
visualstudioexptteam.vscodeintellicode-1.2.10/
wallabyjs.quokka-vscode-1.0.315/
wwm.better-align-1.1.6/
yummygum.city-lights-icon-vsc-1.1.3/
yummygum.city-lights-theme-1.1.8/
```

**Comment by Arthie** [comment]
Hello Tim, thanks for the excellent report! I was able to reproduce the issue. 
Please try updating the extension to the latest release (v0.1.5).

Removing ` from CompletionItemProvider trigger characters fixed the issue.

**Comment by mugoosse** [comment]
@Arthie fyi your [latest commit](https://github.com/Arthie/vscode-tailwindcssinjs/commit/86781c9fed26bbb9b8383de70ff05b4234c401e5) ('solving' this issue) introduces a very unpleasant UX change that took me hours to track down. See below:

![Large GIF (810x528)](https://user-images.githubusercontent.com/3253186/91911740-a203af00-eca9-11ea-9ec9-033d2e714070.gif)

To get rid of it, I had to disable the plugin. I can imagine other people encountering the same issue as me so it might be good publishing a new version reverting this change for now.

**Comment by Arthie** [comment]
@mugoosse Thank you for taking the time to find this issue. So sorry for the inconvenience! v0.1.6 fixes both issues!

**Comment by timfee** [comment]
Thanks @Arthie  :)
