### ISSUE TITLE
Feature request (or documentation request :)), using ! shorthand via twin.macro

### ISSUE THREAD

**Issue by timfee** [Arthie/vscode-tailwindcssinjs#3]
Hi there,

Thanks so much for the tweaks earlier this week. One thing that's starting to pop up as a result:

When using [twin.macro](https://github.com/ben-rogerson/twin.macro/) and using the `!` shorthand that ~= `!important`, it's starting to throw errors:

<img width="1079" alt="Screen Shot 2020-09-02 at 7 04 30 AM" src="https://user-images.githubusercontent.com/3246342/91993716-91bff400-ecea-11ea-9671-40ca42747d06.png">

As this plugin is more generalized, I can see why it wouldn't recognize this syntax. If it wouldn't break things, delimiting the tailwind classes by whitespace and punctuation might be a quick fix. 

Otherwise, it'd be great to have some supported way to allow this syntax :) 

Thanks again!

**Comment by timfee** [comment]
The world's ugliest fix, for my local environment, was in [packages/typescript-plugin/src/plugin.ts](https://github.com/Arthie/tailwindcssinjs/blob/master/packages/typescript-plugin/src/plugin.ts#L99):

I just added a `.replace('!','')` to `twClass.text` - which totally is the wrong thing to do in the real world 😭 

Perhaps there's some more sturdy regexp to filter out extra characters that may not be of consequence?

**Comment by Arthie** [comment]
Hello,

I added a setting that allows you to ignore errors that match a regex pattern string.
This is available in extension version 0.1.7!

Add this to your VS code `settings.json` to ignore the twin.macro important syntax

```json
  "tailwindcssinjs.ignoreErrors": "\\w+!",
```

**Comment by timfee** [comment]
Who's awesome? @Arthie is awesome! Thank you :)
