### ISSUE TITLE
Support variant

### ISSUE THREAD

**Issue by IRediTOTO** [Arthie/vscode-tailwindcssinjs#6]
Hi i am using your pack, it really helpfull, thank you so much. Just request feature about hint variant :) 
![image](https://user-images.githubusercontent.com/15695252/101232259-3b948f80-36e3-11eb-9e43-986615649ff3.png)

**Comment by IRediTOTO** [comment]
And let support Tw 2.0 too :D 

![image](https://user-images.githubusercontent.com/15695252/101232403-0e94ac80-36e4-11eb-8948-0a23d026a23b.png)

**Comment by Arthie** [comment]
Tailwind 2.x is supported with the new extension [xwind](https://marketplace.visualstudio.com/items?itemName=Arthie.vscode-xwind)

The extension only supports default Tailwind variants and variants added with Tailwind plugins.
You can tell the extension to ignore this error by adding a regex pattern string to the `xwind.ignoreErrors` option in your VS code settings.
